version: '3'

services:
  api:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '${API_SERVER_PORT}:${API_SERVER_PORT}'
    depends_on:
      - db
    networks:
      - postgres

  db:
    build: .docker/postgres/
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /postgresql/data
    volumes:
      - db:/postgresql/data
    networks:
      - postgres
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

networks:
  postgres:
    driver: bridge

volumes:
  db: {}
